- name : play 1
  hosts: ubuntu
  tasks:
    - name: inst nginx
      apt: 
         name: nginx
         state: latest
    
    - name: index.html
      copy:
       content: "<h1>Hello GALAXY</h1>"
       dest: /var/www/html/index.html

    - name: start nginx
      service:
        name: nginx
        state: started
        enabled: yes 


- name: play 2
  hosts: webserver
  tasks:
    - name: installing httpd and wget
      yum:
        pkg: "{{ item }}"
        state: present
      loop:
        - httpd
        - wget

    - name: start Apache
      service:
       name: httpd
       state: restarted
       enabled: yes

- name: play 3
  hosts: node1
  tasks:
    - name: configure nginx node 1
      copy:
       src: /home/ec2-user/index.html
       dest: /var/www/html/index.html
